image: node:latest

before_script:
  - yarn install

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/
test:
  stage: test
  script:
    - CI=true yarn test

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://aloha-staging.herokuapp.com
  only:
    - develop
  script:
    - echo "Staging deployment"
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_API_STAGING_KEY

deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://alohaapp.herokuapp.com
  only:
    - master
  script:
    - echo "Production deployment"
    # - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/alohaapp.git
    # - git push heroku master