image: node:latest

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install

build:
  stage: build
  script:
    - yarn build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
      paths:
        - build/

test:
  stage: test
  script:
    - CI=true yarn test

deploy_staging:
  stage: deploy
  environment:
    name: staging
  only:
    - develop
  script:
    - echo "Staging deploy"

deploy_production:
  stage: deploy
  environment:
    name: production
  only:
    - master
  script:
    - echo "Production deploy"