image: node:latest

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install

build:
  stage: build
  script:
    - yarn build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/
test:
  stage: test
  script:
    - CI=true yarn test

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://aloha-staging.herokuapp.com
  only:
    - develop
  script:
    - echo "Staging deploy"
    # - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/aloha-staging.git
    # - git push heroku develop:master

deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://alohaapp.herokuapp.com
  only:
    - master
  script:
    - echo "Production deploy"
    # - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/alohaapp.git
    # - git push heroku master